"""empty message

Revision ID: b7aeb2cb8d98
Revises: 10e23ffaa6c0
Create Date: 2023-10-02 13:58:46.948458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7aeb2cb8d98'
down_revision = '10e23ffaa6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vyrobky',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('Vyrobce_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Vyrobce_id'], ['vyrobce.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vyrobky')
    # ### end Alembic commands ###
